# Generated by Django 4.1 on 2024-11-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagescarousel',
            name='image',
            field=models.ImageField(upload_to='media/carousel'),
        ),
    ]
