# Generated by Django 4.2.16 on 2024-11-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sortablebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortableCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('image', models.ImageField(upload_to='carousel')),
                ('my_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'ordering': ['my_order'],
            },
        ),
        migrations.DeleteModel(
            name='ImagesCarousel',
        ),
        migrations.DeleteModel(
            name='SortableBook',
        ),
    ]
