# Generated by Django 4.1 on 2024-12-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sortablecarousel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sortablecarousel',
            options={'ordering': ['my_order'], 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
    ]
